<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MoviesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $movies = array (
            0 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BN2UwZjg1ZjEtMDc5Ni00MTYyLTkzMmMtYjYxZmFhYzYyMGZmXkEyXkFqcGc@._V1_QL75_UY562_CR234,0,380,562_.jpg',
                    'title' => 'Pillion',
                    'year' => '2025',
                    'summary' => 'Colin, un hombre reservado, se vincula inesperadamente con Ray, un carismático líder de moteros. Ray lo inicia en una dinámica sumisa, sacudiendo su rutina y fomentando su crecimiento personal.',
                    'genres' => 'Drama, Romance',
                    'runtime' => '1h 43m',
                    'director' => 'Harry Lighton',
                    'cast' => 'Alexander Skarsgård, Harry Melling, Douglas Hodge',
                    'rating' => '7,3',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/LeV8jdmmQWM',
                ),
            1 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BYjkxNGVjYmItNzlhMS00ZjA0LWJlMmMtNTUzMThmNTY0ODA3XkEyXkFqcGc@._V1_QL75_UX380_CR0,20,380,562_.jpg',
                    'title' => 'M3GAN 2.0',
                    'year' => '2025',
                    'summary' => 'Dos años después del incidente M3GAN, Gemma revive su muñeca AI para enfrentar a Amelia, un robot militar creado por contratistas que robaron la tecnología de M3GAN.',
                    'genres' => 'Acción, Terror, Ciencia ficción, Suspense',
                    'runtime' => '2h',
                    'director' => 'Gerard Johnstone',
                    'cast' => 'Allison Williams, Ivanna Sakhno, Jenna Davis',
                    'rating' => '6,4',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/IYLHdEzsk1s',
                ),
            2 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BZGQ5NGEyYTItMjNiMi00Y2EwLTkzOWItMjc5YjJiMjMyNTI0XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Misión: Imposible - Sentencia final',
                    'year' => '2025',
                    'summary' => 'Ethan y su equipo tienen la misión de encontrar y destruir a una IA conocida como La Entidad. El viaje por todo el mundo da lugar a increíbles escenas de acción y a más de un giro inesperado.',
                    'genres' => 'Acción, Aventura, Suspense',
                    'runtime' => '2h 49m',
                    'director' => 'Christopher McQuarrie',
                    'cast' => 'Tom Cruise, Hayley Atwell, Ving Rhames',
                    'rating' => '7,5',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/A6VZHeeZGgk',
                ),
            3 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BOWUyM2Y5YWMtZTUzZC00ODBiLTg1N2QtNGMzOTNkOTVjMDY4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Lilo y Stitch',
                    'year' => '2025',
                    'summary' => 'Una solitaria niña hawaiana se hace amiga de un extraterrestre fugitivo y ayuda a sanar a su fragmentada familia.',
                    'genres' => 'Acción, Aventura, Comedia',
                    'runtime' => '1h 48m',
                    'director' => 'Dean Fleischer Camp',
                    'cast' => 'Maia Kealoha, Sydney Agudong, Chris Sanders',
                    'rating' => '7,0',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/VWqJifMMgZE',
                ),
            4 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNTUwNzJhOWMtN2E2NC00NWQxLWI1NTctZTY0MzZiZGNiOGFjXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Destino final: Lazos de sangre',
                    'year' => '2025',
                    'summary' => 'Atormentada por una pesadilla violenta recurrente, una estudiante universitaria regresa a casa para encontrar a la única persona que puede romper el ciclo y salvar a su familia del horrible destino que inevitablemente les espera.',
                    'genres' => 'Terror',
                    'runtime' => '1h 50m',
                    'director' => 'Zach Lipovsky, Adam B. Stein',
                    'cast' => 'Kaitlyn Santa Juana, Teo Briones, Rya Kihlstedt',
                    'rating' => '7,0',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/8FudANSsWNQ',
                ),
            5 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNWRlZmU3ZTItM2JlYi00YTg1LTgxNTItMjMyNzIyZWY5YWJmXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'La fuente de la eterna juventud',
                    'year' => '2025',
                    'summary' => 'Dos hermanos unen sus fuerzas para buscar la legendaria fuente de la juventud. Utilizando pistas históricas, se embarcan en una búsqueda épica llena de aventuras. Si tienen éxito, la mítica fuente podría concederles la inmortalidad.',
                    'genres' => 'Acción, Aventura, Fantasía',
                    'runtime' => '2h 5m',
                    'director' => 'Guy Ritchie',
                    'cast' => 'John Krasinski, Natalie Portman, Eiza González',
                    'rating' => '5,7',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/6NW6Qz915oA',
                ),
            6 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMWY3MzM1Y2YtZWIzOS00ZWJiLWI1YzYtZDY5MzFkY2I4ZjY5XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Los pecadores',
                    'year' => '2025',
                    'summary' => 'Tratando de descubrir sus problemáticas vidas detrás, los hermanos gemelos regresan a su ciudad natal para comenzar de nuevo, solo para descubrir que un mal aún mayor los espera para darles la bienvenida nuevamente.',
                    'genres' => 'Acción, Drama, Terror',
                    'runtime' => '2h 17m',
                    'director' => 'Ryan Coogler',
                    'cast' => 'Michael B. Jordan, Miles Caton, Saul Williams',
                    'rating' => '8,0',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/wAxwRnRvGXc',
                ),
            7 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNjJlMDJjZTctNDlkYi00YTNmLWIyZjUtZjdmZTFhNDQwMTQ4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'La calle del terror: La reina del baile',
                    'year' => '2025',
                    'summary' => 'En la ciudad de Shadyside, Ohio, se acerca el baile de graduación. Las chicas populares compiten por la corona. Pronto, las chicas comienzan a desaparecer misteriosamente.',
                    'genres' => 'Terror, Misterio, Suspense',
                    'runtime' => '1h 30m',
                    'director' => 'Matt Palmer',
                    'cast' => 'India Fowler, Suzanna Son, Fina Strazza',
                    'rating' => '5,2',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/-Y5F-VodcGo',
                ),
            8 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMDM3ZTVkMGUtYjcyNi00NGY1LTlkY2ItZWJhODk1MjZiZGU0XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Thunderbolts*',
                    'year' => '2025',
                    'summary' => 'Un mundo sin Vengadores no significa que no haya un grupo de superhéroes. Hay un grupo y se llaman Thunderbolts.',
                    'genres' => 'Acción, Aventura, Crimen',
                    'runtime' => '2h 7m',
                    'director' => 'Jake Schreier',
                    'cast' => 'Florence Pugh, Sebastian Stan, Julia Louis-Dreyfus',
                    'rating' => '7,6',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/hUUszE29jS0',
                ),
            9 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BODM0M2M4YWQtMzhlNy00NjdkLWFkODktOGNlNTc4OTFiZjZmXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Nonnas',
                    'year' => '2025',
                    'summary' => 'Joe Scaravella, se da cuenta de que ha perdido el tiempo como soltero en un trabajo sin futuro y anhela una segunda oportunidad, abre un restaurante y contrata a un grupo de abuelas como chefs.',
                    'genres' => 'Comedia',
                    'runtime' => '1h 51m',
                    'director' => 'Stephen Chbosky',
                    'cast' => 'Vince Vaughn, Lorraine Bracco, Talia Shire',
                    'rating' => '6,9',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/rDJxJd3FzDY',
                ),
            10 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BZTg0YzRkNDMtZTJjZS00Mjk0LTgwNGQtZWIzMTM3ZDRmZTQwXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Misión: Imposible - Sentencia mortal. Parte Uno',
                    'year' => '2023',
                    'summary' => 'Séptima entrega de la saga \'Misión Imposible\'.',
                    'genres' => 'Acción, Aventura, Suspense',
                    'runtime' => '2h 43m',
                    'director' => 'Christopher McQuarrie',
                    'cast' => 'Tom Cruise, Hayley Atwell, Ving Rhames',
                    'rating' => '7,6',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/XoDmKCZBeeI',
                ),
            11 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BY2I5MmUxZGMtNTI0MC00OWU0LThjZjMtMDRjYTNmZDdkYmJhXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Mickey 17',
                    'year' => '2025',
                    'summary' => 'Mickey participa en una expedición humana para colonizar el planeta helado Niflheim. Es un "prescindible", un empleado descartable. Cada vez que muere, sus recuerdos se implantan en un nuevo cuerpo y su misión se reanuda.',
                    'genres' => 'Aventura, Comedia, Fantasía',
                    'runtime' => '2h 17m',
                    'director' => 'Bong Joon Ho',
                    'cast' => 'Robert Pattinson, Steven Yeun, Michael Monroe',
                    'rating' => '6,8',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/osYpGSz_0i4',
                ),
            12 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNzg5MTNkOTQtZDU2ZC00MjM3LTk1MDAtMTYyZDFmN2Y2MTY5XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Until Dawn',
                    'year' => '2025',
                    'summary' => 'Un grupo pasa el fin de semana en un refugio de esquí en el aniversario de la desaparición de sus amigos, sin saber que no están solos.',
                    'genres' => 'Drama, Terror',
                    'runtime' => '1h 43m',
                    'director' => 'David F. Sandberg',
                    'cast' => 'Ella Rubin, Michael Cimino, Odessa A\'zion',
                    'rating' => '5,8',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/2b3vBaINZ7w',
                ),
            13 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMGJjMDZiNzYtOWNjNS00MmYwLTg4NjAtYTJmYjZmODBlMzYzXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Una película de Minecraft',
                    'year' => '2025',
                    'summary' => 'El malvado dragón de Ender está en su camino a la destrucción, haciendo que una chica joven y su grupo de aventureros amigos intenten salvar Overworld.',
                    'genres' => 'Acción, Aventura, Comedia',
                    'runtime' => '1h 41m',
                    'director' => 'Jared Hess',
                    'cast' => 'Jason Momoa, Jack Black, Sebastian Hansen',
                    'rating' => '5,7',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/bwAbeOvpfq0',
                ),
            14 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BYmQxZGIxNTYtYTQwMy00ODdkLWI0MmQtM2E0ZmIyNmYzMGMzXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'A Working Man',
                    'year' => '2025',
                    'summary' => 'Levon Cade dejó su profesión para trabajar en la construcción. Pero cuando una chica de la localidad desaparece, se le pide que retome las habilidades que le convirtieron en una figura mítica en la lucha antiterrorista.',
                    'genres' => 'Acción, Suspense',
                    'runtime' => '1h 56m',
                    'director' => 'David Ayer',
                    'cast' => 'Jason Statham, Jason Flemyng, Merab Ninidze',
                    'rating' => '5,7',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/zTbgNC42Ops',
                ),
            15 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BODhhMjU4ZGItZjEzZC00MzM1LWEyMTEtMDhmOTNiN2Y3MDg5XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Blancanieves',
                    'year' => '2025',
                    'summary' => 'Una princesa une fuerzas con siete enanitos y un grupo de rebeldes para liberar su reino de su cruel madrastra, la Reina Malvada.',
                    'genres' => 'Aventura, Familiar, Fantasía',
                    'runtime' => '1h 49m',
                    'director' => 'Marc Webb',
                    'cast' => 'Rachel Zegler, Emilia Faucher, Gal Gadot',
                    'rating' => '1,7',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/BE0BwFSYXOQ',
                ),
            16 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BZWMwNTc4NjItNzJhZC00OWY5LWE2NGYtMzkwNTZmOTI4YWMzXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Destino final',
                    'year' => '2000',
                    'summary' => 'Alex Browning forma parte de un grupo de estudiantes de secundaria que se prepara para un viaje a Europa. Cuando tiene una premonición de que su avión se va a estrellar, grita para avisar a los demás, pero es expulsado del avión.',
                    'genres' => 'Terror, Suspense',
                    'runtime' => '1h 38m',
                    'director' => 'James Wong',
                    'cast' => 'Devon Sawa, Ali Larter, Kerr Smith',
                    'rating' => '6,7',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/pCiWxIHw7bQ',
                ),
            17 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BYzk2MjdkZDMtNmU0ZC00ZTEyLTk0ZTAtZDM1MmFhNDdhMjFiXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'La hermanastra fea',
                    'year' => '2025',
                    'summary' => 'En una retorcida versión del clásico cuento de Cenicienta, "La hermanastra fea" sigue a Elvira en su lucha por competir con su increíblemente bella hermanastra. En un reino de cuento de hadas donde la belleza es un negocio brutal.',
                    'genres' => 'Comedia, Drama, Terror',
                    'runtime' => '1h 49m',
                    'director' => 'Emilie Blichfeldt',
                    'cast' => 'Lea Myren, Ane Dahl Torp, Thea Sofie Loch Næss',
                    'rating' => '7,0',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/JVlVSnIhQjU',
                ),
            18 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNTJmODQzYmItNTZlMy00Mjg0LTk1NjctYjM4ZGI0NTM3ZTVjXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'El esquema fenicio',
                    'year' => '2025',
                    'summary' => 'Una oscura historia de espionaje que sigue a una tensa relación padre-hija en un negocio familiar. Los giros giran en torno a la traición y las elecciones moralmente grises.',
                    'genres' => 'Acción, Comedia, Crimen',
                    'runtime' => '1h 41m',
                    'director' => 'Wes Anderson',
                    'cast' => 'Benicio Del Toro, Mia Threapleton, Michael Cera',
                    'rating' => '6,8',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/EK_xkN9fxnM',
                ),
            19 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMzZhODk0NDktMjJjOC00NThjLWE5MDctNmUzYjA3MjIwNDA0XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Warfare: Tiempo de guerra',
                    'year' => '2025',
                    'summary' => 'Basado en las experiencias reales del ex Navy Seal Ray Mendoza durante la guerra de Irak.',
                    'genres' => 'Acción, Drama, Bélico',
                    'runtime' => '1h 35m',
                    'director' => 'Alex Garland, Ray Mendoza',
                    'cast' => 'D\'Pharaoh Woon-A-Tai, Will Poulter, Cosmo Jarvis',
                    'rating' => '7,4',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/U2fyVaevw3o',
                ),
            20 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMzljN2M1MWMtYmUwMi00YWM5LTllMGItNzZlMmU1NWM2NTY5XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Friendship',
                    'year' => '2024',
                    'summary' => 'Cuando el nuevo vecino Brian amenaza su tranquila vida, Craig Waterman lucha por proteger la seguridad de su familia.',
                    'genres' => 'Comedia',
                    'runtime' => '1h 40m',
                    'director' => 'Andrew DeYoung',
                    'cast' => 'Tim Robinson, Paul Rudd, Kate Mara',
                    'rating' => '7,5',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/cmSPwZIZu6Y',
                ),
            21 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMjgyMDE3ZGEtYmJjNS00MzI1LTk5ZmUtZTc4OGQzZWJlODk4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Mission: Impossible',
                    'year' => '1996',
                    'summary' => 'Un agente americano, bajo falsas sospechas de deslealtad, debe descubrir y desenmascarar al verdadero espía sin la ayuda de su organización.',
                    'genres' => 'Acción, Aventura, Suspense',
                    'runtime' => '1h 50m',
                    'director' => 'Brian De Palma',
                    'cast' => 'Tom Cruise, Jon Voight, Emmanuelle Béart',
                    'rating' => '7,2',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/L8Pbjh4EZRk',
                ),
            22 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMjEwMzMxODIzOV5BMl5BanBnXkFtZTgwNzg3OTAzMDI@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Rogue One: Una historia de Star Wars',
                    'year' => '2016',
                    'summary' => 'La hija de un científico imperial se une a la Alianza Rebelde en una arriesgada jugada para robar los planos de la Estrella de la Muerte.',
                    'genres' => 'Acción, Aventura, Ciencia ficción',
                    'runtime' => '2h 13m',
                    'director' => 'Gareth Edwards',
                    'cast' => 'Felicity Jones, Diego Luna, Alan Tudyk',
                    'rating' => '7,8',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/Xcs4OpUJWrM',
                ),
            23 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BZWJjMjdhNGEtZjEyMi00OTg2LTllMzQtN2JlZWNjYzI4YzFhXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Estragos',
                    'year' => '2025',
                    'summary' => 'Tras un negocio de drogas que sale mal, un detective magullado debe abrirse camino a través del submundo criminal para rescatar al hijo distanciado de un político, desentrañando una profunda red de corrupción que atrapa a toda su ciudad.',
                    'genres' => 'Acción, Crimen, Drama',
                    'runtime' => '1h 47m',
                    'director' => 'Gareth Evans',
                    'cast' => 'Tom Hardy, Jessie Mei Li, Justin Cornwell',
                    'rating' => '5,7',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/9mqXX2cn5SA',
                ),
            24 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BYThlZjg0MmItMjViYy00NjQ1LWJlOWQtMzIxMzI4NjhiMDA1XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'El contable 2',
                    'year' => '2025',
                    'summary' => 'Christian Wolff aplica su mente brillante y sus métodos poco legales para reconstruir el rompecabezas sin resolver del asesinato de un jefe de Hacienda.',
                    'genres' => 'Acción, Crimen, Drama',
                    'runtime' => '2h 12m',
                    'director' => 'Gavin O\'Connor',
                    'cast' => 'Ben Affleck, Jon Bernthal, Cynthia Addai-Robinson',
                    'rating' => '7,0',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/i2R_Ac7bBL4',
                ),
            25 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNTY1MDg1MWYtZmJkMC00Y2I2LWFhNmItYmUxZjRiODk3OGNiXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Misión: Imposible - Fallout',
                    'year' => '2018',
                    'summary' => 'Ethan Hunt y su equipo del FMI, junto con algunos aliados conocidos, corren contrarreloj después de que una misión saliera mal.',
                    'genres' => 'Acción, Aventura, Suspense',
                    'runtime' => '2h 27m',
                    'director' => 'Christopher McQuarrie',
                    'cast' => 'Tom Cruise, Henry Cavill, Ving Rhames',
                    'rating' => '7,7',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/wb49-oV0F78',
                ),
            26 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMzg1MDk5NTMtZjQ5Mi00ZmRlLTg3ZTUtZTFlZGQ1YzBhMjcwXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Karate Kid: Legends',
                    'year' => '2025',
                    'summary' => 'Daniel llega a Beijing, donde el Sr. Han lo ha estado buscando. Han tiene un nuevo protegido, Li Fong. Los dos mentores deben colaborar para instruir a Li Fong, pero queda por ver si sus enfoques educativos serán compatibles.',
                    'genres' => 'Acción, Drama, Familiar',
                    'runtime' => '1h 34m',
                    'director' => 'Jonathan Entwistle',
                    'cast' => 'Jackie Chan, Ben Wang, Joshua Jackson',
                    'rating' => '6,5',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/AclxHKf3x30',
                ),
            27 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNDQ2MGIyNDQtYjVhOS00ZjI1LWFmYzctMWI2MGZhZGFhZWM4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Untitled the Weeknd & Trey Edward Shults Project',
                    'year' => '2025',
                    'summary' => 'Un músico que sufre de insomnio se topa con un enigmático desconocido, desencadenando una aventura que pondrá en duda toda su realidad.',
                    'genres' => 'Suspense',
                    'runtime' => '1h 45m',
                    'director' => 'Trey Edward Shults',
                    'cast' => 'The Weeknd, Jenna Ortega, Barry Keoghan',
                    'rating' => '5,3',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/hg0oFI2egfo',
                ),
            28 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMjdkNzJlYzgtY2MwZC00NWFjLTgwMDgtOTJkY2Q3NjA3MjMzXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Ballerina',
                    'year' => '2025',
                    'summary' => 'Una asesina entrenada por la Ruska Roma desde su infancia, la misma organización criminal encargada del adiestramiento de John Wick, intentará por todos los medios averiguar quién está detrás del asesinato de su padre.',
                    'genres' => 'Acción, Suspense',
                    'runtime' => '2h 5m',
                    'director' => 'Len Wiseman',
                    'cast' => 'Ana de Armas, Keanu Reeves, Ian McShane',
                    'rating' => '',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/0FSwsrFpkbw',
                ),
            29 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BOWM4MjIxZmQtYzA3YS00YThiLWI5MjItZDM0YjZmNDFhZDA3XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'The Legend of Ochi',
                    'year' => '2025',
                    'summary' => 'Una niña descubre los misterios de la comunicación animal.',
                    'genres' => 'Aventura, Familiar, Fantasía',
                    'runtime' => '1h 35m',
                    'director' => 'Isaiah Saxon',
                    'cast' => 'Helena Zengel, Willem Dafoe, Emily Watson',
                    'rating' => '6,0',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/_jTFLg3arYU',
                ),
            30 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BN2FhYjgzYTctZDcyZS00MTdlLWIzYzUtOGIyMTYzZWJkYzc4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Confidencial (Black Bag)',
                    'year' => '2025',
                    'summary' => 'En un viaje de autodescubrimiento, un hombre se enfrenta al deber de amar y defender su patria, encontrándose en tres encrucijadas vitales.',
                    'genres' => 'Drama, Misterio, Romance',
                    'runtime' => '1h 33m',
                    'director' => 'Steven Soderbergh',
                    'cast' => 'Michael Fassbender, Gustaf Skarsgård, Cate Blanchett',
                    'rating' => '6,8',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/AVFM-uAbPtA',
                ),
            31 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNjQyMjNiMDEtOTFlNy00NmI3LTljMzctNDU5ZDI3N2EzNDFmXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'La acompañante',
                    'year' => '2025',
                    'summary' => 'La muerte de un multimillonario desencadena una serie de acontecimientos para Iris y sus amigos durante un viaje de fin de semana a su finca junto al lago.',
                    'genres' => 'Ciencia ficción, Suspense',
                    'runtime' => '1h 37m',
                    'director' => 'Drew Hancock',
                    'cast' => 'Sophie Thatcher, Jack Quaid, Lukas Gage',
                    'rating' => '6,9',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/22xmiGr9gNc',
                ),
            32 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMGQ1MTAzNmItOWQ0Ny00MDJhLWJkZmMtYWY2MWY3OTE3MjU2XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Novocaine',
                    'year' => '2025',
                    'summary' => 'Un hombre introvertido y apacible nace con un extraño trastorno genético que le hace inmune al dolor físico. Cuando su nueva novia es tomada como rehén en el atraco a un banco, su aflicción se convierte en su superpoder.',
                    'genres' => 'Acción, Comedia, Suspense',
                    'runtime' => '1h 50m',
                    'director' => 'Dan Berk, Robert Olsen',
                    'cast' => 'Jack Quaid, Amber Midthunder, Ray Nicholson',
                    'rating' => '6,5',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/BmYcuswoQBY',
                ),
            33 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNGJiMzU2M2MtMjMyNC00YmFmLTljYjgtNWIzNDI5ZjE2YjZjXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Cónclave',
                    'year' => '2024',
                    'summary' => 'Sigue al cardenal Lomeli mientras supervisa al grupo de cardenales encargados de elegir a un nuevo líder de la Iglesia, al tiempo que intenta descubrir un secreto del difunto Pontífice.',
                    'genres' => 'Drama, Suspense',
                    'runtime' => '2h',
                    'director' => 'Edward Berger',
                    'cast' => 'Ralph Fiennes, Stanley Tucci, John Lithgow',
                    'rating' => '7,4',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/aMiOsqSkcYg',
                ),
            34 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMjIxODZlM2EtODU5Ny00OTFkLTgyNjAtNzNmMWJkNmRhZjZkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Gladiator II',
                    'year' => '2024',
                    'summary' => 'Años después de presenciar la muerte del héroe Máximo a manos de su tío, Lucio se ve forzado a entrar en el Coliseo tras ser testigo de la conquista de su hogar por parte de los tiránicos emperadores que dirigen Roma con puño de hierro.',
                    'genres' => 'Acción, Aventura, Drama',
                    'runtime' => '2h 28m',
                    'director' => 'Ridley Scott',
                    'cast' => 'Paul Mescal, Denzel Washington, Pedro Pascal',
                    'rating' => '6,5',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/4rgYUipGJNo',
                ),
            35 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMWUwYmJmNDYtNjJhNi00ZjZiLWFhNzktYjEyMWQ5NWM3MmE5XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => '28 años después',
                    'year' => '2025',
                    'summary' => 'Trama no develada. Tercera película de la franquicia "28 días después".',
                    'genres' => 'Terror, Suspense',
                    'runtime' => '1h 55m',
                    'director' => 'Danny Boyle',
                    'cast' => 'Jack O\'Connell, Ralph Fiennes, Aaron Taylor-Johnson',
                    'rating' => '',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/d-4F7jJUoOE',
                ),
            36 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BY2E5YjE2YTQtZGIxYi00YTU4LTk3YzItYmMyZTM3M2I5ZTM3XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Cómo entrenar a tu dragón',
                    'year' => '2025',
                    'summary' => 'Un joven vikingo aspira a cazar dragones, pero se convierte inesperadamente en amigo de un joven dragón.',
                    'genres' => 'Acción, Aventura, Comedia',
                    'runtime' => '2h 5m',
                    'director' => 'Dean DeBlois',
                    'cast' => 'Mason Thames, Nico Parker, Gerard Butler',
                    'rating' => '',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/liGB1ssYn38',
                ),
            37 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BOTEwOTdhMTEtMzkyZS00MzdhLTk0N2ItMzBjZjA0OTg2NjZlXkEyXkFqcGc@._V1_QL75_UX380_CR0,2,380,562_.jpg',
                    'title' => 'Die My Love',
                    'year' => '2025',
                    'summary' => 'En una remota zona rural olvidada, una madre lucha por mantener la cordura mientras lucha contra la psicosis.',
                    'genres' => 'Comedia, Suspense',
                    'runtime' => '1h 58m',
                    'director' => 'Lynne Ramsay',
                    'cast' => 'Jennifer Lawrence, Robert Pattinson, Nick Nolte',
                    'rating' => '6,5',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/yGILHjmOEjw',
                ),
            38 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNzY1MzdjMjYtNDJiZS00N2U4LWI0MWQtZTRiZWYxMzU3ZmI4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Misión: Imposible 3',
                    'year' => '2006',
                    'summary' => 'Agente del IMF Ethan Hunt se enfrenta a un peligroso y sádico traficante de armas que amenaza su vida y la de su prometida.',
                    'genres' => 'Acción, Aventura, Suspense',
                    'runtime' => '2h 6m',
                    'director' => 'J.J. Abrams',
                    'cast' => 'Tom Cruise, Michelle Monaghan, Ving Rhames',
                    'rating' => '6,9',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/3iCoDJaFPOA',
                ),
            39 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BZmI5NjIyZmMtMjBhOC00NGE0LTkwZDYtMzFkMDY1MDQ0NWQxXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Destino final 2',
                    'year' => '2003',
                    'summary' => 'Kimberly tiene una premonición sobre una colisión múltiple y mantiene a salvo a algunos de los destinados a morir. La muerte acecha a ese grupo de supervivientes.',
                    'genres' => 'Terror, Suspense',
                    'runtime' => '1h 30m',
                    'director' => 'David R. Ellis',
                    'cast' => 'A.J. Cook, Ali Larter, Tony Todd',
                    'rating' => '6,2',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/7vZqVooni2o',
                ),
            40 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNTViNGI0MzMtYTJlMS00Y2NiLTg5MDYtZTE3NTY1OWY3YmU3XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Robot salvaje',
                    'year' => '2024',
                    'summary' => 'La robot Roz, que ha naufragado en una isla deshabitada, debe aprender a adaptarse al duro entorno, forjando poco a poco relaciones con la fauna local y convirtiéndose en madre adoptiva de una cría de ganso huérfana.',
                    'genres' => 'Animación, Ciencia ficción',
                    'runtime' => '1h 42m',
                    'director' => 'Chris Sanders',
                    'cast' => 'Lupita Nyong\'o, Pedro Pascal, Kit Connor',
                    'rating' => '8,2',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/UPgUIORqja4',
                ),
            41 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BZWY5ZmYyMDctZTA3YS00ODY1LTgyMjEtOTA3YmNhMmY2NWNlXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Misión: Imposible - Protocolo fantasma',
                    'year' => '2011',
                    'summary' => 'El IMF es clausurado cuando se ve incriminado en un ataque bomba al Kremlin. Ethan Hunt y su nuevo equipo se embarcan en un misión clandestina para limpiar el nombre de la organización.',
                    'genres' => 'Acción, Aventura, Suspense',
                    'runtime' => '2h 12m',
                    'director' => 'Brad Bird',
                    'cast' => 'Tom Cruise, Jeremy Renner, Simon Pegg',
                    'rating' => '7,4',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/RIcuey5eHgc',
                ),
            42 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BOWM0YjkwNTYtNDYxNS00NTk5LWEwYzEtN2U0MzQyYTA3ODkyXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Misión: Imposible 2',
                    'year' => '2000',
                    'summary' => '"El agente del FMI Ethan Hunt es enviado a Sydney, para encontrar y destruir una enfermedad genéticamente modificada llamada ""Quimera""."',
                    'genres' => 'Acción, Aventura, Suspense',
                    'runtime' => '2h 3m',
                    'director' => 'John Woo',
                    'cast' => 'Tom Cruise, Dougray Scott, Thandiwe Newton',
                    'rating' => '6,1',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            43 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BZTlhYTk1ZTEtOWY3NC00NWQ5LTlkOTctNjQ3ZDYyZGE5ZWNlXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Bring Her Back',
                    'year' => '2025',
                    'summary' => 'Un hermano y una hermana descubren un ritual aterrador en la apartada casa de su nueva madre adoptiva.',
                    'genres' => 'Terror, Misterio',
                    'runtime' => '1h 44m',
                    'director' => 'Danny Philippou, Michael Philippou',
                    'cast' => 'Billy Barratt, Sally Hawkins, Mischa Heywood',
                    'rating' => '7,7',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            44 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BYTA2NTA5NDYtMzlkOC00MTQxLWI0NDQtMzk2M2YzMGE4MTkxXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'A Complete Unknown',
                    'year' => '2024',
                    'summary' => 'En 1961, un desconocido de 19 años llamado Bob Dylan llegó a Nueva York sólo con su guitarra. Conoció a iconos de la música folk y pronto se hizo notar por su talento.',
                    'genres' => 'Biografía, Drama, Música',
                    'runtime' => '2h 21m',
                    'director' => 'James Mangold',
                    'cast' => 'Timothée Chalamet, Edward Norton, Elle Fanning',
                    'rating' => '7,4',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            45 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNmE0NGQ5NmUtNWY3OS00MjRjLTgyZTYtNWY3Y2E3YTEzYzg0XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Anora',
                    'year' => '2024',
                    'summary' => 'Anora, una joven trabajadora sexual de Brooklyn, conoce a Ivan, el hijo de un oligarca. Se casan por capricho. Su cuento de hadas se ve amenazado cuando los padres de Iván se enteran de la noticia y deciden anular el matrimonio.',
                    'genres' => 'Comedia, Drama, Romance',
                    'runtime' => '2h 19m',
                    'director' => 'Sean Baker',
                    'cast' => 'Mikey Madison, Paul Weissman, Yura Borisov',
                    'rating' => '7,5',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            46 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMDBhNTg1MWMtMDc5Ni00YTk1LWFjNGUtMmE2Y2Q5MGQ2M2Q2XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Otro pequeño favor',
                    'year' => '2025',
                    'summary' => 'Sigue a Stephanie Smothers y Emily Nelson cuando se dirigen a la hermosa isla de Capri, Italia, para la extravagante boda de Emily con un rico hombre de negocios italiano.',
                    'genres' => 'Comedia, Crimen, Misterio',
                    'runtime' => '2h',
                    'director' => 'Paul Feig',
                    'cast' => 'Blake Lively, Anna Kendrick, Allison Janney',
                    'rating' => '5,3',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            47 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMTgyOTExNDc1M15BMl5BanBnXkFtZTcwMDA0MTA4NQ@@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Destino final 5',
                    'year' => '2011',
                    'summary' => 'La muerte vuelve para reclamar a los afortunados supervivientes del derrumbe de un mortífero puente.',
                    'genres' => 'Terror, Suspense',
                    'runtime' => '1h 32m',
                    'director' => 'Steven Quale',
                    'cast' => 'Nicholas D\'Agosto, Emma Bell, Arlen Escarpeta',
                    'rating' => '5,9',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            48 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BOWM1NWVmMGQtZTUzNC00NzAwLWIzMmMtMmUwMmQwYzY3MjVkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Destino final 3',
                    'year' => '2006',
                    'summary' => 'Una adolescente tiene la premonición de que ella y sus amigos se verán involucrados en un accidente en una montaña rusa. Cuando la visión se hace realidad, los supervivientes se enfrentan a las repercusiones de haber engañado a la muerte.',
                    'genres' => 'Terror, Suspense',
                    'runtime' => '1h 33m',
                    'director' => 'James Wong',
                    'cast' => 'Mary Elizabeth Winstead, Ryan Merriman, Kris Lemche',
                    'rating' => '5,9',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            49 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNGQ0YTY2OWEtMmFhZC00MjFjLWEwODMtMjFkMjRmZjNlNGRhXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'El destino final',
                    'year' => '2009',
                    'summary' => 'Una espeluznante premonición salva a un joven y a sus amigos de la muerte durante un accidente en una pista de carreras, pero a pesar de ello les espera un destino terrible.',
                    'genres' => 'Terror, Suspense',
                    'runtime' => '1h 22m',
                    'director' => 'David R. Ellis',
                    'cast' => 'Nick Zano, Krista Allen, Andrew Fiscella',
                    'rating' => '5,1',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            50 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNDcwMmIwMTUtZGNkZC00Nzk0LTgzOWQtYTJiMTVlMzRlMmJkXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Sentimental Value',
                    'year' => '2025',
                    'summary' => 'Una exploración íntima y conmovedora de la familia, los recuerdos y el poder reconciliador del arte.',
                    'genres' => 'Comedia, Drama',
                    'runtime' => '2h 12m',
                    'director' => 'Joachim Trier',
                    'cast' => 'Renate Reinsve, Stellan Skarsgård, Inga Ibsdotter Lilleaas',
                    'rating' => '7,9',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            51 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BZTBhNTE0OTgtMTkxYy00OTZhLWE2MjQtZDNkMjgyNzE4ODA1XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'La cita',
                    'year' => '2025',
                    'summary' => 'En su primera cita en años, la viuda Violet ve truncado su romance con el encantador Henry al recibir siniestros mensajes anónimos.',
                    'genres' => 'Drama, Misterio, Suspense',
                    'runtime' => '1h 35m',
                    'director' => 'Christopher Landon',
                    'cast' => 'Meghann Fahy, Brandon Sklenar, Violett Beane',
                    'rating' => '6,1',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            52 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BZTU1MzU1YzctMDQ1MS00ZmRhLWFkZmYtZmNjM2YwYzIwMDgxXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'The Hunger Games: Sunrise on the Reaping',
                    'year' => '2026',
                    'summary' => 'Explora Panem 24 años antes de la saga de Katniss, comenzando en la mañana de la siega de los 50º Juegos del Hambre, donde participa un joven Haymitch Abernathy.',
                    'genres' => 'Acción, Aventura, Fantasía',
                    'runtime' => '',
                    'director' => 'Francis Lawrence',
                    'cast' => 'Elle Fanning, Jesse Plemons, Ralph Fiennes',
                    'rating' => '',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            53 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BOWMyMDk5MjAtNDM4Mi00Y2Y3LTg3YTktNzk3NjAxNDc2OTdmXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Los 4 Fantásticos: Primeros pasos',
                    'year' => '2025',
                    'summary' => 'La primera familia de Marvel se enfrenta a su mayor desafío hasta la fecha. Obligados a equilibrar su papel de héroes con la fuerza de su vínculo familiar, deben defender la Tierra de un voraz dios del espacio llamado Galactus.',
                    'genres' => 'Acción, Aventura, Ciencia ficción',
                    'runtime' => '2h 10m',
                    'director' => 'Matt Shakman',
                    'cast' => 'Pedro Pascal, Vanessa Kirby, Joseph Quinn',
                    'rating' => '',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            54 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMWJkMzMyZmYtMjc1NC00ODBlLWJjMzUtZWJhMDc4NjVkYzU4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'La sustancia',
                    'year' => '2024',
                    'summary' => 'El terror corporal: La poderosa re-lectura feminista de Fargeat',
                    'genres' => 'Drama, Terror, Ciencia ficción',
                    'runtime' => '2h 21m',
                    'director' => 'Coralie Fargeat',
                    'cast' => 'Demi Moore, Margaret Qualley, Dennis Quaid',
                    'rating' => '7,2',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            55 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMTA1MjE0Nzk4MDleQTJeQWpwZ15BbWU4MDA0NjIxMjAx._V1_QL75_UY207_CR6,0,140,207_.jpg',
                    'title' => 'Cadena perpetua',
                    'year' => '1994',
                    'summary' => 'Andy Dufresne es encarcelado por matar a su esposa y al amante de esta. Tras una dura adaptación, intenta mejorar las condiciones de la prisión y dar esperanza a sus compañeros.',
                    'genres' => 'Drama',
                    'runtime' => '2h 22m',
                    'director' => 'Frank Darabont',
                    'cast' => 'Tim Robbins, Morgan Freeman, Bob Gunton',
                    'rating' => '9,3',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            56 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Interstellar',
                    'year' => '2014',
                    'summary' => 'Un equipo de exploradores viaja a través de un agujero de gusano en el espacio en un intento de garantizar la supervivencia de la humanidad.',
                    'genres' => 'Aventura, Drama, Ciencia ficción',
                    'runtime' => '2h 49m',
                    'director' => 'Christopher Nolan',
                    'cast' => 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
                    'rating' => '8,7',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            57 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BYjVkMzI2MjAtYzA3NC00OGE1LWEyZDMtODc0YTc5NTZjYzFiXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Exterritorial',
                    'year' => '2025',
                    'summary' => 'Cuando el hijo de un soldado desaparece en un consulado de los Estados Unidos, ella permanece ilegalmente en las instalaciones para buscarlo y, sin saberlo, se ve envuelta en una peligrosa conspiración.',
                    'genres' => 'Acción, Misterio, Suspense',
                    'runtime' => '1h 49m',
                    'director' => 'Christian Zübert',
                    'cast' => 'Jeanne Goursaud, Dougray Scott, Lera Abova',
                    'rating' => '5,7',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            58 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNGUzY2Y0ZmItZDE4Ny00OGE2LWI0MjQtNzY2YjRmNTRkMTZiXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Nosferatu',
                    'year' => '2024',
                    'summary' => 'Una historia gótica de obsesión entre una joven encantada en la Alemania del siglo XIX y el antiguo vampiro de Transilvania que la acecha y trae consigo un horror incalculable.',
                    'genres' => 'Fantasía, Terror, Misterio',
                    'runtime' => '2h 12m',
                    'director' => 'Robert Eggers',
                    'cast' => 'Lily-Rose Depp, Nicholas Hoult, Bill Skarsgård',
                    'rating' => '7,2',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            59 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNDRjY2E0ZmEtN2QwNi00NTEwLWI3MWItODNkMGYwYWFjNGE0XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Capitán América: Brave New World',
                    'year' => '2025',
                    'summary' => 'La trama se mantiene en secreto. Cuarta película de la franquicia del Capitán América.',
                    'genres' => 'Acción, Aventura, Ciencia ficción',
                    'runtime' => '1h 58m',
                    'director' => 'Julius Onah',
                    'cast' => 'Anthony Mackie, Harrison Ford, Danny Ramirez',
                    'rating' => '5,7',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            60 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMTU0YjAxOTctMzY3MC00M2Q2LTlhMDItZDk0YjhjMzViYWU0XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Babygirl',
                    'year' => '2024',
                    'summary' => 'A pesar del riesgo y los prejuicios, una directora ejecutiva muy exitosa comienza una aventura ilícita con su becario mucho más joven.',
                    'genres' => 'Drama, Romance, Suspense',
                    'runtime' => '1h 54m',
                    'director' => 'Halina Reijn',
                    'cast' => 'Nicole Kidman, Harris Dickinson, Antonio Banderas',
                    'rating' => '5,9',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            61 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BOTQ5Y2QyYTktYmFmZi00NWJlLWE0MzgtYTA4M2I0ZjQwZjcxXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'El abismo secreto',
                    'year' => '2025',
                    'summary' => 'Dos jóvenes muy peligrosos que, a pesar del mundo corrupto y letal en el que se mueven, encuentran un alma gemela el uno en el otro.',
                    'genres' => 'Acción, Aventura, Terror',
                    'runtime' => '2h 7m',
                    'director' => 'Scott Derrickson',
                    'cast' => 'Miles Teller, Anya Taylor-Joy, Sigourney Weaver',
                    'rating' => '6,7',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            62 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BY2IzOWJlMzktYmUxMy00MmY2LWJiZTgtYTQ0MjQyOGRmNWNiXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Heretic (Hereje)',
                    'year' => '2024',
                    'summary' => 'Sigue a dos jóvenes religiosas que se involucran en un juego del gato y el ratón en la casa de un extraño.',
                    'genres' => 'Terror, Suspense',
                    'runtime' => '1h 51m',
                    'director' => 'Scott Beck, Bryan Woods',
                    'cast' => 'Hugh Grant, Sophie Thatcher, Chloe East',
                    'rating' => '7,0',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            63 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNmQxMTI1YmEtOGY3Yi00NzVlLWEzMjAtYTI1NWZkNDFiMDg1XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Materialistas',
                    'year' => '2025',
                    'summary' => 'Una joven y ambiciosa casamentera de la ciudad de Nueva York se encuentra dividida entre su pareja perfecta y su ex imperfecto.',
                    'genres' => 'Comedia, Romance',
                    'runtime' => '1h 49m',
                    'director' => 'Celine Song',
                    'cast' => 'Dakota Johnson, Chris Evans, Pedro Pascal',
                    'rating' => '',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            64 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMjRhOTgwOTEtZmNhOC00OTc1LTlhODYtZDdkYzJiMmZhYmYxXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => '28 días después',
                    'year' => '2002',
                    'summary' => 'Cuatro semanas después de que un misterioso e incurable virus se extienda por todo el Reino Unido, un puñado de supervivientes intenta encontrar refugio.',
                    'genres' => 'Drama, Terror, Ciencia ficción',
                    'runtime' => '1h 53m',
                    'director' => 'Danny Boyle',
                    'cast' => 'Cillian Murphy, Naomie Harris, Christopher Eccleston',
                    'rating' => '7,5',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            65 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMDBkZDNjMWEtOTdmMi00NmExLTg5MmMtNTFlYTJlNWY5YTdmXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Top Gun: Maverick',
                    'year' => '2022',
                    'summary' => 'Después de más de treinta años de servicio como uno de los mejores aviadores de la Armada, Pete Mitchell está donde pertenece, forzando los límites como valiente piloto de pruebas y esquivando el avance de rango que lo dejaría en tierra.',
                    'genres' => 'Acción, Drama',
                    'runtime' => '2h 10m',
                    'director' => 'Joseph Kosinski',
                    'cast' => 'Tom Cruise, Jennifer Connelly, Miles Teller',
                    'rating' => '8,2',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            66 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNjUzMjhkZjktNTU5Mi00MzhmLWJhMTQtZjhkYjczOTEzM2M5XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Death of a Unicorn',
                    'year' => '2025',
                    'summary' => 'El dúo padre-hija, Riley y Elliot, atropellan a un unicornio con su coche y lo llevan al refugio natural de un director general farmacéutico mega-rico.',
                    'genres' => 'Comedia, Fantasía, Terror',
                    'runtime' => '1h 47m',
                    'director' => 'Alex Scharfman',
                    'cast' => 'Paul Rudd, Jenna Ortega, Will Poulter',
                    'rating' => '5,9',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            67 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BOWNiMGQxYzAtNzc1Yy00NTNjLWIwNmEtNzcyZjk2ZDYyMzM1XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'El contable',
                    'year' => '2016',
                    'summary' => 'Cuando un experto en matemáticas blanquea los libros de un nuevo cliente, el Departamento del Tesoro se acerca a sus actividades, y el número de cadáveres empieza a aumentar.',
                    'genres' => 'Acción, Crimen, Drama',
                    'runtime' => '2h 8m',
                    'director' => 'Gavin O\'Connor',
                    'cast' => 'Ben Affleck, Anna Kendrick, J.K. Simmons',
                    'rating' => '7,3',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            68 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNjQyOTRiYTQtNzU0MS00ZGM2LWE4MTktODI5ZjZiN2NkYjYyXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Raid 2',
                    'year' => '2025',
                    'summary' => 'En Rajastán 1989, el oficial Patnaik efectúa una redada sin éxito. Tras solicitar un soborno, le trasladan a Bhoj, donde investiga a Dada Bhai, figura respetada. Suspendido tras otra redada, descubre secretos.',
                    'genres' => 'Crimen, Drama, Suspense',
                    'runtime' => '2h 25m',
                    'director' => 'Raj Kumar Gupta',
                    'cast' => 'Ajay Devgn, Riteish Deshmukh, Vaani Kapoor',
                    'rating' => '7,2',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            69 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BZjlkZWQ2YjAtOTZjNi00MmY1LTlkMDMtYTUxODU5Y2Y0MDY4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Agente secreto',
                    'year' => '2025',
                    'summary' => 'Bajo el espectro amenazador del Brasil de 1977, conocemos a Marcelo, un hombre de unos 40 años que se ha mudado recientemente a Recife, en la costa noreste de Brasil, para escapar de un pasado violento.',
                    'genres' => 'Crimen, Drama, Historia',
                    'runtime' => '2h 38m',
                    'director' => 'Kleber Mendonça Filho',
                    'cast' => 'Wagner Moura, Maria Fernanda Cândido, Gabriel Leone',
                    'rating' => '7,9',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            70 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BODE1M2NhOTYtMmFmNi00NTUwLWI5YzEtN2ZhNDhjMWZmNWViXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Zootrópolis 2',
                    'year' => '2025',
                    'summary' => 'La policía coneja Judy Hopps y su amigo el zorro Nick Wilde vuelven a unirse para resolver su caso más peligroso y complejo.',
                    'genres' => 'Animación, Acción, Aventura',
                    'runtime' => '',
                    'director' => 'Jared Bush, Byron Howard',
                    'cast' => 'Jason Bateman, Quinta Brunson, Fortune Feimster',
                    'rating' => '',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            71 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMzQ3OTI0ZTUtMzkwMC00MzZhLWJiZmYtODFmZjZmMmJiMTc5XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Alpha',
                    'year' => '2025',
                    'summary' => 'Alpha, de 13 años, es una adolescente problemática que vive sola con su madre. Su mundo se derrumba el día que regresa de la escuela con un tatuaje en el brazo.',
                    'genres' => 'Drama',
                    'runtime' => '2h 8m',
                    'director' => 'Julia Ducournau',
                    'cast' => 'Tahar Rahim, Golshifteh Farahani, Mélissa Boros',
                    'rating' => '5,2',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            72 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BODM2NTUxOGMtM2ZkYS00MjM3LTkzYzEtZjdkNmQ1ZTBhMWY3XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Un simple accidente',
                    'year' => '2025',
                    'summary' => 'Un pequeño percance provocó una reacción en cadena de problemas cada vez mayores.',
                    'genres' => 'Acción, Aventura, Crimen',
                    'runtime' => '1h 41m',
                    'director' => 'Jafar Panahi',
                    'cast' => 'Vahid Mobasseri, Mariam Afshari, Ebrahim Azizi',
                    'rating' => '7,4',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            73 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BYjgzMTgyNzYtZjMzZS00NGRmLWE2YTAtMDQ4NTA3N2FmNmNhXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Amateur',
                    'year' => '2025',
                    'summary' => 'Sigue a un criptógrafo de la CIA, que consigue chantajear a su agencia para que le entrenen y le dejen ir tras un grupo de terroristas que mataron a su mujer en Londres.',
                    'genres' => 'Acción, Suspense',
                    'runtime' => '2h 2m',
                    'director' => 'James Hawes',
                    'cast' => 'Rami Malek, Rachel Brosnahan, Jon Bernthal',
                    'rating' => '6,7',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            74 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNjNhODY5OWEtZjMxNy00NzFhLWIzOTQtZTNmYjUwOGRiMzYwXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'The Diplomat',
                    'year' => '2025',
                    'summary' => 'Un diplomático indio que intenta repatriar a una niña india desde Pakistán, donde presumiblemente la obligaron y engañaron para que se casara contra su voluntad.',
                    'genres' => 'Drama, Suspense',
                    'runtime' => '2h 10m',
                    'director' => 'Shivam Nair',
                    'cast' => 'John Abraham, Sadia Khateeb, Kumud Mishra',
                    'rating' => '7,1',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            75 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNTljNjllNDAtMzc0MS00ZGExLThlOTktOTRlNzc3YjA3ZWFlXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'El padrino',
                    'year' => '1972',
                    'summary' => 'El envejecido patriarca de una dinastía del crimen organizado en la ciudad de Nueva York de la posguerra transfiere el control de su imperio clandestino a su reacio hijo menor.',
                    'genres' => 'Crimen, Drama',
                    'runtime' => '2h 55m',
                    'director' => 'Francis Ford Coppola',
                    'cast' => 'Marlon Brando, Al Pacino, James Caan',
                    'rating' => '9,2',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            76 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BZmJhZjI4ODktNjI3MC00N2U2LTg0YzYtZTgzNTk4NDJkNmVhXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'The Surrender',
                    'year' => '2025',
                    'summary' => 'Cuando el patriarca de la familia muere, una madre y una hija afligidas arriesgan sus vidas para llevar a cabo un brutal ritual de resurrección y resucitarlo de entre los muertos.',
                    'genres' => 'Drama, Terror, Suspense',
                    'runtime' => '1h 36m',
                    'director' => 'Julia Max',
                    'cast' => 'Colby Minifie, Kate Burton, Chelsea Alden',
                    'rating' => '5,5',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            77 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNzUzYmUyZDYtYTM5My00MjhkLTk2NDEtZmRiODEzOWE1MzRmXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Un pequeño favor',
                    'year' => '2018',
                    'summary' => 'Una mujer intenta descubrir la verdad tras la desaparición de su mejor amiga.',
                    'genres' => 'Comedia, Crimen, Misterio',
                    'runtime' => '1h 57m',
                    'director' => 'Paul Feig',
                    'cast' => 'Anna Kendrick, Blake Lively, Henry Golding',
                    'rating' => '6,8',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            78 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BOGUwNzQwMzYtZTkyYi00OTM3LWJiOGEtNzVkN2UxOGZlMmE3XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Clown in a Cornfield',
                    'year' => '2025',
                    'summary' => 'Frendo, un payaso que encarna la gloria desvanecida de un pueblo, regresa como una fuerza siniestra en una localidad del Medio Oeste en decadencia, sembrando terror.',
                    'genres' => 'Terror, Misterio, Suspense',
                    'runtime' => '1h 36m',
                    'director' => 'Eli Craig',
                    'cast' => 'Katie Douglas, Aaron Abrams, Carson MacCormac',
                    'rating' => '6,2',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            79 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNzZhMTc5MWUtOTE2MS00MjUwLTljYWEtYTk1ZmVjNzhmMzYzXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'The Monkey',
                    'year' => '2025',
                    'summary' => 'Cuando los gemelos Bill y Hal encuentran el viejo juguete del mono de su padre, comienzan una serie de muertes espantosas. Los hermanos deciden tirar el juguete y seguir adelante con sus vidas, distanciándose con el paso de los años.',
                    'genres' => 'Terror',
                    'runtime' => '1h 38m',
                    'director' => 'Osgood Perkins',
                    'cast' => 'Theo James, Tatiana Maslany, Christian Convery',
                    'rating' => '6,0',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            80 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BZGRhNjU2NWEtNDNmYy00YmEwLWFiMTEtZDA5YmFmYmJkMThhXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Familia al instante',
                    'year' => '2018',
                    'summary' => 'Una pareja se siente desbordada tras decidir experimentar la paternidad convirtiéndose en padres de acogida de tres niños revoltosos.',
                    'genres' => 'Comedia, Drama',
                    'runtime' => '1h 58m',
                    'director' => 'Sean Anders',
                    'cast' => 'Mark Wahlberg, Rose Byrne, Isabela Merced',
                    'rating' => '7,3',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            81 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNTQwYjM2YjUtOWM0Ni00ODgyLTg4NjQtODU2NDI5YjM2ZWQzXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Bitelchús Bitelchús',
                    'year' => '2024',
                    'summary' => 'Tras una tragedia familiar, tres generaciones de la familia Deetz regresan a Winter River. Todavía atormentada por Bitelchús, la vida de Lydia da un vuelco cuando su hija adolescente, Astrid, abre accidentalmente el portal al Más Allá.',
                    'genres' => 'Comedia, Fantasía, Terror',
                    'runtime' => '1h 45m',
                    'director' => 'Tim Burton',
                    'cast' => 'Michael Keaton, Winona Ryder, Catherine O\'Hara',
                    'rating' => '6,6',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            82 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNzBiMTQ0YjMtZDRhMC00ZDU4LTk3MDMtNWQxOGMwMjQzYjc4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Dune: Parte dos',
                    'year' => '2024',
                    'summary' => 'El duque Paul Atreides se une a los Fremen y comienza su entrenamiento para convertirse en Muad\'Dib, mientras trata de evitar el terrible futuro que ha previsto: una guerra santa en su nombre, esparciéndose por todo el universo conocido.',
                    'genres' => 'Acción, Aventura, Drama',
                    'runtime' => '2h 46m',
                    'director' => 'Denis Villeneuve',
                    'cast' => 'Timothée Chalamet, Zendaya, Rebecca Ferguson',
                    'rating' => '8,5',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            83 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BZDZlZjY4NGMtNWIwNC00OWVhLTkyMmUtODI5ZDY4MmFhODllXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Gladiator (El gladiador)',
                    'year' => '2000',
                    'summary' => 'Un exgeneral romano se propone vengarse del emperador corrupto que asesinó a su familia y lo envió a la esclavitud.',
                    'genres' => 'Acción, Aventura, Drama',
                    'runtime' => '2h 35m',
                    'director' => 'Ridley Scott',
                    'cast' => 'Russell Crowe, Joaquin Phoenix, Connie Nielsen',
                    'rating' => '8,5',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            84 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMDVlMTQyYTgtNjUyZS00Y2E1LTlmMTktMDJkM2E1YzFiMzQxXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Bala perdida',
                    'year' => '2025',
                    'summary' => 'El exjugador de béisbol Hank Thompson se ve envuelto en una peligrosa lucha por la supervivencia en medio del submundo criminal de la ciudad de Nueva York de los 90, obligado a navegar por un traicionero inframundo que nunca imaginó.',
                    'genres' => 'Comedia, Crimen, Suspense',
                    'runtime' => '',
                    'director' => 'Darren Aronofsky',
                    'cast' => 'Austin Butler, Zoë Kravitz, Vincent D\'Onofrio',
                    'rating' => '',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            85 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNTQxYmM1NzQtY2FiZS00MzRhLTljZDYtZjRmMGNiMWI3NTQxXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Origen',
                    'year' => '2010',
                    'summary' => 'A un ladrón que roba secretos corporativos a través del uso de la tecnología de compartir sueños, se le da la tarea de implantar una idea en la mente de un jefe de una gran empresa.',
                    'genres' => 'Acción, Aventura, Ciencia ficción',
                    'runtime' => '2h 28m',
                    'director' => 'Christopher Nolan',
                    'cast' => 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page',
                    'rating' => '8,8',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            86 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BZWFhZDJiODYtZTA5My00NWYyLTgzY2YtOTUwMGYxZTFkYzdjXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Rosario',
                    'year' => '2025',
                    'summary' => 'Rosario pasa la noche con el cuerpo de su abuela mientras espera a que llegue la ambulancia, durante una fuerte nevada, Rosario es atacada por entidades de otro mundo que han tomado el control del cuerpo de su abuela.',
                    'genres' => 'Terror',
                    'runtime' => '1h 28m',
                    'director' => 'Felipe Vargas',
                    'cast' => 'David Dastmalchian, Emeraude Toubia, José Zúñiga',
                    'rating' => '4,4',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            87 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNmRmMjc5MWMtMzZmMy00NTYzLTgwZDQtNTAyMmNlYmIxOTg2XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Las cuatro estaciones',
                    'year' => '1981',
                    'summary' => 'Tres parejas van de vacaciones juntas cada temporada. Tras el divorcio de una de ellas, surgen sentimientos de traición y más críticas hacia la otra, pero las cosas que las mantienen unidas son más fuertes que las que podrían separarlas.',
                    'genres' => 'Comedia, Drama',
                    'runtime' => '1h 47m',
                    'director' => 'Alan Alda',
                    'cast' => 'Alan Alda, Carol Burnett, Len Cariou',
                    'rating' => '6,8',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            88 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'El caballero oscuro',
                    'year' => '2008',
                    'summary' => 'Cuando la amenaza conocida como el Joker causa estragos y el caos en Gotham City, Batman debe aceptar una de las mayores pruebas psicológicas y físicas para luchar contra la injusticia.',
                    'genres' => 'Acción, Crimen, Drama',
                    'runtime' => '2h 32m',
                    'director' => 'Christopher Nolan',
                    'cast' => 'Christian Bale, Heath Ledger, Aaron Eckhart',
                    'rating' => '9,0',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            89 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNTFlZDI1YWQtMTVjNy00YWU1LTg2YjktMTlhYmRiYzQ3NTVhXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Oppenheimer',
                    'year' => '2023',
                    'summary' => 'La historia del científico J. Robert Oppenheimer y su rol en el desarrollo de la bomba atómica.',
                    'genres' => 'Biografía, Drama, Historia',
                    'runtime' => '3h',
                    'director' => 'Christopher Nolan',
                    'cast' => 'Cillian Murphy, Emily Blunt, Matt Damon',
                    'rating' => '8,3',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            90 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BOWFjMGIwNDgtODE5MS00ZWVkLTlhNzgtMDI1ZDM1OWMyYzY4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'La evaluación',
                    'year' => '2024',
                    'summary' => 'Después de una catástrofe climática, una sociedad aparentemente perfecta pone a prueba a una pareja durante una semana para ver si están aptos para la paternidad. Un evaluador analiza cada aspecto de sus vidas.',
                    'genres' => 'Drama, Ciencia ficción',
                    'runtime' => '1h 54m',
                    'director' => 'Fleur Fortune',
                    'cast' => 'Alicia Vikander, Elizabeth Olsen, Himesh Patel',
                    'rating' => '6,6',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            91 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNGU3YTdiM2EtY2Y3MC00NTIzLWEzYzYtM2IxZDNhZjkwNjU1XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'La guerra de las galaxias',
                    'year' => '1977',
                    'summary' => 'Luke Skywalker une sus fuerzas con un caballero jedi, un piloto fanfarrón, un wookiee y dos droides para salvar a la galaxia de la estación espacial del Imperio, a la vez que intenta rescatar a la princesa Leia del malvado Darth Vader.',
                    'genres' => 'Acción, Aventura, Fantasía',
                    'runtime' => '2h 1m',
                    'director' => 'George Lucas',
                    'cast' => 'Mark Hamill, Harrison Ford, Carrie Fisher',
                    'rating' => '8,6',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => '',
                ),
            92 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMGNiN2RlZTMtMTkyZC00YjkwLTgyY2QtMDg1ZDNhODQwNWM4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Avengers: Doomsday',
                    'year' => '2026',
                    'summary' => 'Trama en secreto.',
                    'genres' => 'Acción, Aventura, Ciencia ficción',
                    'runtime' => '',
                    'director' => 'Anthony Russo, Joe Russo',
                    'cast' => 'Robert Downey Jr., Pedro Pascal, Chris Hemsworth',
                    'rating' => '6,0',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-26 05:42:00',
                    'trailer' => '',
                ),
            93 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BOWRiOThkM2YtYzI4NS00OWViLTk0ODMtMjNlNDYyZWQ3MzNjXkEyXkFqcGc@._V1_QL75_UY562_CR35,0,380,562_.jpg',
                    'title' => 'F1',
                    'year' => '2025',
                    'summary' => 'Sigue a un piloto de Fórmula Uno que sale de su retiro para convertirse en mentor y formar equipo con un piloto más joven.',
                    'genres' => 'Acción, Drama, Deporte',
                    'runtime' => '2h 35m',
                    'director' => 'Joseph Kosinski',
                    'cast' => 'Brad Pitt, Javier Bardem, Kerry Condon',
                    'rating' => '',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 19:45:49',
                    'trailer' => 'https://www.youtube.com/embed/8yh9BPUBbbQ',
                ),
            94 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BODlkOTkyOTgtY2M3My00MmVmLWE0YzYtOWRhMDZjNDkwMzI2XkEyXkFqcGc@._V1_QL75_UX380_CR0,20,380,562_.jpg',
                    'title' => 'Jurassic World: El renacer',
                    'year' => '2025',
                    'summary' => 'Cinco años después de Jurassic World: Dominion, una expedición se aventura en remotas regiones ecuatoriales para extraer ADN de tres enormes criaturas prehistóricas, con el objetivo de lograr un avance médico revolucionario.',
                    'genres' => 'Acción, Aventura, Ciencia ficción',
                    'runtime' => '2h 14m',
                    'director' => 'Gareth Edwards',
                    'cast' => 'Scarlett Johansson, Rupert Friend, Jonathan Bailey',
                    'rating' => '',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/1R3LTANp7hw',
                ),
            95 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMWFiZjUwZmEtMGVjYi00MjI0LTk5MzAtMjM0MjRkODcyNjI5XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Superman',
                    'year' => '2025',
                    'summary' => 'Sigue al superhéroe titular mientras reconcilia su herencia con su educación humana. Es la encarnación de la verdad, la justicia y un mañana mejor en un mundo que ve la bondad como algo anticuado.',
                    'genres' => 'Acción, Aventura, Fantasía',
                    'runtime' => '2h 2m',
                    'director' => 'James Gunn',
                    'cast' => 'David Corenswet, Rachel Brosnahan, Nicholas Hoult',
                    'rating' => '',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/Ox8ZLF6cGM0',
                ),
            96 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BYzRiYTA1YTEtMjYwMi00NGVhLThkOGYtZDBlYjNjZDk2NDEwXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Lilo & Stitch',
                    'year' => '2002',
                    'summary' => 'Una niña hawaiana adopta a supuesto un perro, sin saber que es un peligroso experimento científico que se ha refugiado en la Tierra y que ahora se esconde de su creador y de quienes lo ven como una amenaza.',
                    'genres' => 'Animación, Aventura, Comedia',
                    'runtime' => '1h 25m',
                    'director' => 'Dean DeBlois, Chris Sanders',
                    'cast' => 'Daveigh Chase, Chris Sanders, Tia Carrere',
                    'rating' => '7,3',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/9OAC55UWAQs',
                ),
            97 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BNTMyYzNiZjEtZTM3NC00OGRkLTkzMjEtZGI2NDcwZTk5NmNhXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'The Brutalist',
                    'year' => '2024',
                    'summary' => 'Cuando el visionario arquitecto László Toth y su esposa Erzsébet huyen de la Europa de posguerra en 1947 para reconstruir su legado y ver el nacimiento de la América moderna, sus vidas cambian a causa de un misterioso y adinerado cliente.',
                    'genres' => 'Drama',
                    'runtime' => '3h 36m',
                    'director' => 'Brady Corbet',
                    'cast' => 'Adrien Brody, Felicity Jones, Guy Pearce',
                    'rating' => '7,4',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/GdRXPAHIEW4',
                ),
            98 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BYjkyNmFiYTYtODE4Mi00ZWRlLWI3OWUtY2RjMmYxNzljYWM1XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Misión: Imposible - Nación secreta',
                    'year' => '2015',
                    'summary' => 'Ethan y su equipo asumen su misión más imposible hasta la fecha, erradicar al Sindicato, una organización internacional clandestina tan altamente cualificada como ellos, comprometida con la destrucción del FMI.',
                    'genres' => 'Acción, Aventura, Suspense',
                    'runtime' => '2h 11m',
                    'director' => 'Christopher McQuarrie',
                    'cast' => 'Tom Cruise, Rebecca Ferguson, Jeremy Renner',
                    'rating' => '7,4',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/KhpZIDPY1RU',
                ),
            99 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BMDgzZTgzOTEtMTllZS00ZDdjLWE4NWUtOTkwOTk0Mjk3ODA5XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'Eddington',
                    'year' => '2025',
                    'summary' => 'Una pareja varada en un pequeño pueblo de Nuevo México durante la pandemia encuentra que la comunidad inicialmente acogedora se vuelve siniestra al caer la noche.',
                    'genres' => 'Comedia, Drama, Del oeste',
                    'runtime' => '2h 28m',
                    'director' => 'Ari Aster',
                    'cast' => 'Joaquin Phoenix, Deirdre O\'Connell, Emma Stone',
                    'rating' => '5,8',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/oL6jZqExlIk',
                ),
            100 =>
                array (
                    'movie_poster' => 'https://m.media-amazon.com/images/M/MV5BYTI4NjcwODMtZGVhMi00ODhhLWIwODItZTQ4MmY0ZmU5OTliXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
                    'title' => 'The Last Rodeo',
                    'year' => '2025',
                    'summary' => 'Un ex jinete de rodeo de 50 años distanciado de su hija decide montar de nuevo cuando surge una crisis con su nieto, enfrentando sus demonios y considerando el máximo sacrificio por su familia.',
                    'genres' => 'Drama',
                    'runtime' => '1h 56m',
                    'director' => 'Jon Avnet',
                    'cast' => 'Neal McDonough, Mykelti Williamson, Sarah Jones',
                    'rating' => '6,9',
                    'created_at' => '2025-07-31 05:31:03',
                    'updated_at' => '2025-07-31 05:31:03',
                    'trailer' => 'https://www.youtube.com/embed/ADuANCCW1iw',
                ),
        );

        foreach ($movies as &$movie) {
            $movie['rating'] = $movie['rating'] !== '' ? $movie['rating'] : null;
            $movie['created_at'] = $movie['created_at'] !== '' ? $movie['created_at'] : now();
            $movie['updated_at'] = $movie['updated_at'] !== '' ? $movie['updated_at'] : now();
            $movie['trailer'] = $movie['trailer'] !== '' ? $movie['trailer'] : null;
        }
        unset($movie);

        DB::table('movies')->insert($movies);
    }
}
